### ISSUE TITLE
Проблема с запуском

### ISSUE THREAD

**Issue by dlevsha** [andrienko/markdown-habr#1]
Приветствую. 

На Mac OS после установки вылезает ошибка 

> env: node\r: No such file or directory 

Попробовал запустить вот так

``` bash
node mdhabr
```

Вылезла ошибка 

``` javascript
module.js:338
    throw err;
    ^

Error: Cannot find module '/Users/dlevsha/mdhabr'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

В итоге поставил просто в локальную папку (без флага -g)и запустил как 

``` bash
node bin/mdhabr.js ~/Dropbox/habrahabr-phar-create.md ./test.html
```

В этом случае все сработало. 

А так здорово, вроде действительно все конвертирует. 

Спасибо за Вашу работу :-)

**Comment by andrienko** [comment]
Честно говоря, под макосью не тестил.

Спасибо за инфу: в понедельник отберу у коллеги макбук и посмотрю, что там
;-)

**Comment by andrienko** [comment]
@dlevsha, вроде бы исправил. Вас не затруднит вот сейчас попробовать потестить?)
